spring:
  config:
    activate:
      on-profile: local
#  Failed to start bean 'documentationPluginsBootstrapper' java.lang.NullPointerException exception 이 나면 아래 pathmatch 추가
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#  security:
#    user:
#      name: user
#      password: user
#      roles: manager
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: update
    showSql: true
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
#  security:
#    user:
#      name: user
#      password: user
#      roles: manager
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: update
    showSql: true
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod

#  security:
#    user:
#      name: user
#      password: user
#      roles: manager
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: update
    showSql: true
server:
  port: 8082

